### ISSUE TITLE
macos m1 crash - command not work

### ISSUE THREAD

**Issue by jhonnyalphas** [RoyalFlyBy/PornHubDownloader#14]
./pornhubdownloader -video "https://www.pornhub.com/view_video.php?viewkey=ph6378a03c46eb5"
![Captura de pantalla 2022-12-20 a la(s) 12 03 05 a m](https://user-images.githubusercontent.com/75342360/208587899-e7cc7c77-43c1-4feb-94de-338b97b44b9c.jpg)

**Comment by RoyalFlyBy** [comment]
Thanks for bringing this to my attention, could you please confirm the following things for me:

Do you have writing privileges in the directory/folder you are trying to download in?
Did the program create a file called `.session` in the directory/folder?

I currently have no way to properly test against macos m1, I will try to recreate the issue on Linux and later this week macos x86_64
Good news, this error also occurs on Linux so I will be able to debug it on my end.

**Comment by RoyalFlyBy** [comment]
Rolled out a patch, give it a try

**Comment by jhonnyalphas** [comment]
it's work on my macbook pro m1
