### ISSUE TITLE
i'm getting this error: unsupported proctocol scheme ""

### ISSUE THREAD

**Issue by onupirat** [RoyalFlyBy/PornHubDownloader#2]

**Comment by RoyalFlyBy** [comment]
Could you elaborate on when this error occurs?

It would help a lot if I could recreate the error as accurately as possible

**Comment by onupirat** [comment]
Here's what i get. 
```
C:\Users\onu\Desktop\PornHubDownloader-master>phdownloader.exe -URL=https://www.pornhub.com/view_video.php?viewkey=ph5d796603a8790
[INFO]: 2019/11/02 13:35:23 Logged in with cookie file
[WARNING]:      2019/11/02 13:35:23 If private or premium videos fail you may need to delete the cookie file and run the command again
[INFO]: 2019/11/02 13:35:24 Found the video
[INFO]: 2019/11/02 13:35:24 Downloading: 1080p version
[ERROR]:        2019/11/02 13:35:24 Get : unsupported protocol scheme ""

C:\Users\onu\Desktop\PornHubDownloader-master>
```

Let me know what other info can i provide to you.

**Comment by RoyalFlyBy** [comment]
Sorry for the delay, GitHub notifications never work well for me.
I will be on it tomorrow as I tend to touch up older projects before starting a new one.

The log you have provided is awesome however I would like to know two more things:
1. Are you logged in?
2. Are you a premium member?

I noticed it tries to download the 1080p version, might be a glitch in the program if you are a regular member. (or not even logged in to begin with)

**Comment by onupirat** [comment]
No i'm not logged in nor am a premium member. I don't know if you are aware but 1080p is now avlaible for free users. Also i've heard Pornhub made some changes on their side and because of that many downloaders were broken. This might be the issue.

**Comment by BRUHItsABunny** [comment]
I was not aware they changed their policy to allow free users to watch 1080p however I figured out the cause behind the problem and I will be seeing how to fix it as we speak

Specific information in case other programmers come across this issue:
Previously the video URL's were to be found here:
`var flashvars_247783601 = {"maxInitialBufferLength":10,"disable_sharebar":0,"htmlPauseRoll":"true","htmlPostRoll":"true","errorReports":"https:\/\/www.pornhub.com\/video\/problems\/247783601","autoplay":"true","autoreplay":"false","video_unavailable":"false","pauseroll_url":"","postroll_url":"","embedCode":"<iframe src=\"https:\/\/www.pornhub.com\/embed\/ph5d796603a8790\" frameborder=\"0\" width=\"560\" height=\"340\" scrolling=\"no\" allowfullscreen><\/iframe>","hidePostPauseRoll":false,"isHD":"true","video_duration":"919","actionTags":"","link_url":"https:\/\/www.pornhub.com\/view_video.php?viewkey=ph5d796603a8790","related_url":"https:\/\/www.pornhub.com\/video\/player_related_datas?id=247783601","image_url":"https:\/\/ci.phncdn.com\/videos\/201909\/11\/247783601\/thumbs_30\/(m=eaAaGwObaaaa)(mh=DsPfrd7FSgxzqyMs)12.jpg","video_title":"Best Blowjob Ever. Babe With Red Lipstick Sucks Cock After Cunnilingus.","defaultQuality":[720,480,240,1080],"vcServerUrl":"\/svvt\/add?stype=svv&svalue=247783601&snonce=pb4uygt8bb9jfmlv&skey=fb8b23bc26057ee710337686524f93ef8a0af9fca5df3cd21cc0b51e0700b2a6&stime=1573767181","display_hd_upsell":true,"mediaDefinitions":[{"defaultQuality":false,"format":"mp4","quality":"1080","videoUrl":""},{"defaultQuality":false,"format":"hls","videoUrl":"","quality":"1080"},{"defaultQuality":false,"format":"mp4","quality":"720","videoUrl":""},{"defaultQuality":false,"format":"hls","videoUrl":"","quality":"720"},{"defaultQuality":false,"format":"mp4","quality":"480","videoUrl":""},{"defaultQuality":true,"format":"hls","videoUrl":"","quality":"480"},{"defaultQuality":false,"format":"mp4","quality":"240","videoUrl":""},{"defaultQuality":false,"format":"hls","videoUrl":"","quality":"240"},{"defaultQuality":720,"format":"hls","videoUrl":"","quality":[1080,720,480,240]}];`

Now the obfuscated the URL's like this:

`var rastvlzaidlra40rastvlzaidlra40 = "sTvlZaIdL_";
var rag2k0deikbra57rag2k0deikbra57 = "_G2K0dEiKb";
var radqp5wyfukzra92radqp5wyfukzra92 = "dQp5wYfuKZ";
var raajq0s1wiupra76raajq0s1wiupra76 = "aJQ0s1wiup";
var ra247783601ra55ra247783601ra55 = "24778" + "3601.";
var raheggw6z82ra28raheggw6z82ra28 = "hE-GGW6z8" + "2";
var ra01909112ra71ra01909112ra71 = "01909/1" + "1/2";
var rabbgfpwlwptra74rabbgfpwlwptra74 = "BBgfp" + "wlWPt";
var ragagcp5ntkdra59ragagcp5ntkdra59 = "gaGcp5n" + "TkD";
var raphncdncora30raphncdncora30 = ".phncdn.c" + "o";
var raiy8wbw0ra93raiy8wbw0ra93 = "IY8Wbw0";
var rahttpscvra32rahttpscvra32 = "https://cv";
var ramp4xtkvp8ra62ramp4xtkvp8ra62 = "mp4?XTkvp" + "8";
var raiel31s73emra83raiel31s73emra83 = "IeL31S73eM";
var rar8j1g49r0ra92rar8j1g49r0ra92 = "r8j1G49R0-";
var ra9r8hcyuwbqra94ra9r8hcyuwbqra94 = "9r8hc" + "YUWBq";
var raxdqk5uz8xra74raxdqk5uz8xra74 = "XdqK5" + "uZ8X-";
var ra477836017ra46ra477836017ra46 = "47783" + "601/7";
var rahhlvvpnbira80rahhlvvpnbira80 = "hHLvV" + "PNbI_";
var ra20p1500kra75ra20p1500kra75 = "20P_1" + "500K_";
var ragi764gbkwvra55ragi764gbkwvra55 = "GI764GBkwv";
var rabjeltk37dsra63rabjeltk37dsra63 = "BJeLTK37DS";
var rafoaiy1oumsra90rafoaiy1oumsra90 = "foaIY1oums";
var raewwhomybkrra57raewwhomybkrra57 = "EWWHOMY" + "bKR";
var raryb3uazorkra88raryb3uazorkra88 = "RYb3uazorK";
var ramvideos2ra90ramvideos2ra90 = "m/video" + "s/2";
var ras7gs0wr41hra21ras7gs0wr41hra21 = "S7gS0Wr41H";
var ra97wcjudnenra80ra97wcjudnenra80 = "97wCjudNE" + "n";
var quality_720p = /* + ragi764gbkwvra55ragi764gbkwvra55 + */ rahttpscvra32rahttpscvra32 + /* + ra01909112ra71ra01909112ra71 + */ raphncdncora30raphncdncora30 + /* + radqp5wyfukzra92radqp5wyfukzra92 + */ ramvideos2ra90ramvideos2ra90 + /* + rabbgfpwlwptra74rabbgfpwlwptra74 + */ ra01909112ra71ra01909112ra71 + /* + rar8j1g49r0ra92rar8j1g49r0ra92 + */ ra477836017ra46ra477836017ra46 + /* + ramp4xtkvp8ra62ramp4xtkvp8ra62 + */ ra20p1500kra75ra20p1500kra75 + /* + ra247783601ra55ra247783601ra55 + */ ra247783601ra55ra247783601ra55 + /* + raxdqk5uz8xra74raxdqk5uz8xra74 + */ ramp4xtkvp8ra62ramp4xtkvp8ra62 + /* + raphncdncora30raphncdncora30 + */ raajq0s1wiupra76raajq0s1wiupra76 + /* + raphncdncora30raphncdncora30 + */ radqp5wyfukzra92radqp5wyfukzra92 + /* + ramp4xtkvp8ra62ramp4xtkvp8ra62 + */ ragi764gbkwvra55ragi764gbkwvra55 + /* + ra01909112ra71ra01909112ra71 + */ raewwhomybkrra57raewwhomybkrra57 + /* + ras7gs0wr41hra21ras7gs0wr41hra21 + */ rabjeltk37dsra63rabjeltk37dsra63 + /* + ra477836017ra46ra477836017ra46 + */ rahhlvvpnbira80rahhlvvpnbira80 + /* + radqp5wyfukzra92radqp5wyfukzra92 + */ raxdqk5uz8xra74raxdqk5uz8xra74 + /* + rag2k0deikbra57rag2k0deikbra57 + */ raryb3uazorkra88raryb3uazorkra88 + /* + rabjeltk37dsra63rabjeltk37dsra63 + */ ra97wcjudnenra80ra97wcjudnenra80 + /* + rahttpscvra32rahttpscvra32 + */ rastvlzaidlra40rastvlzaidlra40 + /* + ra9r8hcyuwbqra94ra9r8hcyuwbqra94 + */ rag2k0deikbra57rag2k0deikbra57 + /* + rar8j1g49r0ra92rar8j1g49r0ra92 + */ ra9r8hcyuwbqra94ra9r8hcyuwbqra94 + /* + ra01909112ra71ra01909112ra71 + */ rar8j1g49r0ra92rar8j1g49r0ra92 + /* + rastvlzaidlra40rastvlzaidlra40 + */ ragagcp5ntkdra59ragagcp5ntkdra59 + /* + raiel31s73emra83raiel31s73emra83 + */ rabbgfpwlwptra74rabbgfpwlwptra74 + /* + rahhlvvpnbira80rahhlvvpnbira80 + */ rafoaiy1oumsra90rafoaiy1oumsra90 + /* + ra477836017ra46ra477836017ra46 + */ raheggw6z82ra28raheggw6z82ra28 + /* + raiy8wbw0ra93raiy8wbw0ra93 + */ ras7gs0wr41hra21ras7gs0wr41hra21 + /* + ramvideos2ra90ramvideos2ra90 + */ raiel31s73emra83raiel31s73emra83 + /* + ra247783601ra55ra247783601ra55 + */ raiy8wbw0ra93raiy8wbw0ra93;
flashvars_247783601["quality_720p"] = quality_720p;`

**Comment by RoyalFlyBy** [comment]
I was not aware they changed their policy to allow free users to watch 1080p however I figured out the cause behind the problem and I will be seeing how to fix it as we speak

Specific information in case other programmers come across this issue:
Previously the video URL's were to be found here:
`var flashvars_247783601 = {"maxInitialBufferLength":10,"disable_sharebar":0,"htmlPauseRoll":"true","htmlPostRoll":"true","errorReports":"https:\/\/www.pornhub.com\/video\/problems\/247783601","autoplay":"true","autoreplay":"false","video_unavailable":"false","pauseroll_url":"","postroll_url":"","embedCode":"<iframe src=\"https:\/\/www.pornhub.com\/embed\/ph5d796603a8790\" frameborder=\"0\" width=\"560\" height=\"340\" scrolling=\"no\" allowfullscreen><\/iframe>","hidePostPauseRoll":false,"isHD":"true","video_duration":"919","actionTags":"","link_url":"https:\/\/www.pornhub.com\/view_video.php?viewkey=ph5d796603a8790","related_url":"https:\/\/www.pornhub.com\/video\/player_related_datas?id=247783601","image_url":"https:\/\/ci.phncdn.com\/videos\/201909\/11\/247783601\/thumbs_30\/(m=eaAaGwObaaaa)(mh=DsPfrd7FSgxzqyMs)12.jpg","video_title":"Best Blowjob Ever. Babe With Red Lipstick Sucks Cock After Cunnilingus.","defaultQuality":[720,480,240,1080],"vcServerUrl":"\/svvt\/add?stype=svv&svalue=247783601&snonce=pb4uygt8bb9jfmlv&skey=fb8b23bc26057ee710337686524f93ef8a0af9fca5df3cd21cc0b51e0700b2a6&stime=1573767181","display_hd_upsell":true,"mediaDefinitions":[{"defaultQuality":false,"format":"mp4","quality":"1080","videoUrl":""},{"defaultQuality":false,"format":"hls","videoUrl":"","quality":"1080"},{"defaultQuality":false,"format":"mp4","quality":"720","videoUrl":""},{"defaultQuality":false,"format":"hls","videoUrl":"","quality":"720"},{"defaultQuality":false,"format":"mp4","quality":"480","videoUrl":""},{"defaultQuality":true,"format":"hls","videoUrl":"","quality":"480"},{"defaultQuality":false,"format":"mp4","quality":"240","videoUrl":""},{"defaultQuality":false,"format":"hls","videoUrl":"","quality":"240"},{"defaultQuality":720,"format":"hls","videoUrl":"","quality":[1080,720,480,240]}];`

Now the obfuscated the URL's like this:

`var rastvlzaidlra40rastvlzaidlra40 = "sTvlZaIdL_";
var rag2k0deikbra57rag2k0deikbra57 = "_G2K0dEiKb";
var radqp5wyfukzra92radqp5wyfukzra92 = "dQp5wYfuKZ";
var raajq0s1wiupra76raajq0s1wiupra76 = "aJQ0s1wiup";
var ra247783601ra55ra247783601ra55 = "24778" + "3601.";
var raheggw6z82ra28raheggw6z82ra28 = "hE-GGW6z8" + "2";
var ra01909112ra71ra01909112ra71 = "01909/1" + "1/2";
var rabbgfpwlwptra74rabbgfpwlwptra74 = "BBgfp" + "wlWPt";
var ragagcp5ntkdra59ragagcp5ntkdra59 = "gaGcp5n" + "TkD";
var raphncdncora30raphncdncora30 = ".phncdn.c" + "o";
var raiy8wbw0ra93raiy8wbw0ra93 = "IY8Wbw0";
var rahttpscvra32rahttpscvra32 = "https://cv";
var ramp4xtkvp8ra62ramp4xtkvp8ra62 = "mp4?XTkvp" + "8";
var raiel31s73emra83raiel31s73emra83 = "IeL31S73eM";
var rar8j1g49r0ra92rar8j1g49r0ra92 = "r8j1G49R0-";
var ra9r8hcyuwbqra94ra9r8hcyuwbqra94 = "9r8hc" + "YUWBq";
var raxdqk5uz8xra74raxdqk5uz8xra74 = "XdqK5" + "uZ8X-";
var ra477836017ra46ra477836017ra46 = "47783" + "601/7";
var rahhlvvpnbira80rahhlvvpnbira80 = "hHLvV" + "PNbI_";
var ra20p1500kra75ra20p1500kra75 = "20P_1" + "500K_";
var ragi764gbkwvra55ragi764gbkwvra55 = "GI764GBkwv";
var rabjeltk37dsra63rabjeltk37dsra63 = "BJeLTK37DS";
var rafoaiy1oumsra90rafoaiy1oumsra90 = "foaIY1oums";
var raewwhomybkrra57raewwhomybkrra57 = "EWWHOMY" + "bKR";
var raryb3uazorkra88raryb3uazorkra88 = "RYb3uazorK";
var ramvideos2ra90ramvideos2ra90 = "m/video" + "s/2";
var ras7gs0wr41hra21ras7gs0wr41hra21 = "S7gS0Wr41H";
var ra97wcjudnenra80ra97wcjudnenra80 = "97wCjudNE" + "n";
var quality_720p = /* + ragi764gbkwvra55ragi764gbkwvra55 + */ rahttpscvra32rahttpscvra32 + /* + ra01909112ra71ra01909112ra71 + */ raphncdncora30raphncdncora30 + /* + radqp5wyfukzra92radqp5wyfukzra92 + */ ramvideos2ra90ramvideos2ra90 + /* + rabbgfpwlwptra74rabbgfpwlwptra74 + */ ra01909112ra71ra01909112ra71 + /* + rar8j1g49r0ra92rar8j1g49r0ra92 + */ ra477836017ra46ra477836017ra46 + /* + ramp4xtkvp8ra62ramp4xtkvp8ra62 + */ ra20p1500kra75ra20p1500kra75 + /* + ra247783601ra55ra247783601ra55 + */ ra247783601ra55ra247783601ra55 + /* + raxdqk5uz8xra74raxdqk5uz8xra74 + */ ramp4xtkvp8ra62ramp4xtkvp8ra62 + /* + raphncdncora30raphncdncora30 + */ raajq0s1wiupra76raajq0s1wiupra76 + /* + raphncdncora30raphncdncora30 + */ radqp5wyfukzra92radqp5wyfukzra92 + /* + ramp4xtkvp8ra62ramp4xtkvp8ra62 + */ ragi764gbkwvra55ragi764gbkwvra55 + /* + ra01909112ra71ra01909112ra71 + */ raewwhomybkrra57raewwhomybkrra57 + /* + ras7gs0wr41hra21ras7gs0wr41hra21 + */ rabjeltk37dsra63rabjeltk37dsra63 + /* + ra477836017ra46ra477836017ra46 + */ rahhlvvpnbira80rahhlvvpnbira80 + /* + radqp5wyfukzra92radqp5wyfukzra92 + */ raxdqk5uz8xra74raxdqk5uz8xra74 + /* + rag2k0deikbra57rag2k0deikbra57 + */ raryb3uazorkra88raryb3uazorkra88 + /* + rabjeltk37dsra63rabjeltk37dsra63 + */ ra97wcjudnenra80ra97wcjudnenra80 + /* + rahttpscvra32rahttpscvra32 + */ rastvlzaidlra40rastvlzaidlra40 + /* + ra9r8hcyuwbqra94ra9r8hcyuwbqra94 + */ rag2k0deikbra57rag2k0deikbra57 + /* + rar8j1g49r0ra92rar8j1g49r0ra92 + */ ra9r8hcyuwbqra94ra9r8hcyuwbqra94 + /* + ra01909112ra71ra01909112ra71 + */ rar8j1g49r0ra92rar8j1g49r0ra92 + /* + rastvlzaidlra40rastvlzaidlra40 + */ ragagcp5ntkdra59ragagcp5ntkdra59 + /* + raiel31s73emra83raiel31s73emra83 + */ rabbgfpwlwptra74rabbgfpwlwptra74 + /* + rahhlvvpnbira80rahhlvvpnbira80 + */ rafoaiy1oumsra90rafoaiy1oumsra90 + /* + ra477836017ra46ra477836017ra46 + */ raheggw6z82ra28raheggw6z82ra28 + /* + raiy8wbw0ra93raiy8wbw0ra93 + */ ras7gs0wr41hra21ras7gs0wr41hra21 + /* + ramvideos2ra90ramvideos2ra90 + */ raiel31s73emra83raiel31s73emra83 + /* + ra247783601ra55ra247783601ra55 + */ raiy8wbw0ra93raiy8wbw0ra93;
flashvars_247783601["quality_720p"] = quality_720p;`

**Comment by RoyalFlyBy** [comment]
Rolled out an update that should work, give it a try

**Comment by onupirat** [comment]
Works great, thanks! In case you're interested in developing this project further i can suggest a few things:
1. Add the possibility to download playlists.
2. Add the possibility to download all videos from a specific uploader.
3. Make the progress feedback cleaner. When downloading multiple videos it is not clear how many are done.

**Comment by RoyalFlyBy** [comment]
I may make a GUI version of this program and in that case I would add all of those and probably more features.
Maybe I will add a feature that crawls links from playlists and/or uploaders and throws the links all into one text file to download using the current batch downloading feature.

How would you suggest the progress feedback should look? I'm able to work on that for sure.

Thanks for the feedback

**Comment by onupirat** [comment]
Well, you can tranform this:

```
[INFO]: 2019/11/16 23:17:53 [Found the video]
[INFO]: 2019/11/16 23:17:53 [Downloading: 1080p version]
[INFO]: 2019/11/16 23:17:55 [transferred 4.1 MB / 341 MB bytes (1.20%)]
[INFO]: 2019/11/16 23:17:56 [transferred 9.0 MB / 341 MB bytes (2.63%)]
[INFO]: 2019/11/16 23:17:57 [transferred 14 MB / 341 MB bytes (4.08%)]
[INFO]: 2019/11/16 23:17:58 [transferred 19 MB / 341 MB bytes (5.52%)]
[INFO]: 2019/11/16 23:17:59 [transferred 24 MB / 341 MB bytes (6.98%)]
[INFO]: 2019/11/16 23:18:00 [transferred 29 MB / 341 MB bytes (8.43%)]
[INFO]: 2019/11/16 23:18:01 [transferred 34 MB / 341 MB bytes (9.88%)]
[INFO]: 2019/11/16 23:18:02 [transferred 39 MB / 341 MB bytes (11.34%)]
[INFO]: 2019/11/16 23:18:03 [transferred 44 MB / 341 MB bytes (12.78%)]
[INFO]: 2019/11/16 23:18:04 [transferred 48 MB / 341 MB bytes (14.21%)]
[INFO]: 2019/11/16 23:18:05 [transferred 53 MB / 341 MB bytes (15.67%)]
[INFO]: 2019/11/16 23:18:06 [transferred 57 MB / 341 MB bytes (16.71%)]
[INFO]: 2019/11/16 23:18:07 [transferred 62 MB / 341 MB bytes (18.16%)]
[INFO]: 2019/11/16 23:18:08 [transferred 67 MB / 341 MB bytes (19.61%)]
[INFO]: 2019/11/16 23:18:09 [transferred 72 MB / 341 MB bytes (21.05%)]
[INFO]: 2019/11/16 23:18:10 [transferred 77 MB / 341 MB bytes (22.49%)]
[INFO]: 2019/11/16 23:18:11 [transferred 82 MB / 341 MB bytes (23.95%)]
[INFO]: 2019/11/16 23:18:12 [transferred 86 MB / 341 MB bytes (25.37%)]
[INFO]: 2019/11/16 23:18:13 [transferred 91 MB / 341 MB bytes (26.79%)]
[INFO]: 2019/11/16 23:18:14 [transferred 96 MB / 341 MB bytes (28.25%)]
[INFO]: 2019/11/16 23:18:15 [transferred 101 MB / 341 MB bytes (29.69%)]
[INFO]: 2019/11/16 23:18:16 [transferred 106 MB / 341 MB bytes (31.09%)]
[INFO]: 2019/11/16 23:18:17 [transferred 110 MB / 341 MB bytes (32.17%)]
[INFO]: 2019/11/16 23:18:18 [transferred 114 MB / 341 MB bytes (33.60%)]
[INFO]: 2019/11/16 23:18:19 [transferred 120 MB / 341 MB bytes (35.06%)]
[INFO]: 2019/11/16 23:18:20 [transferred 124 MB / 341 MB bytes (36.49%)]
[INFO]: 2019/11/16 23:18:21 [transferred 129 MB / 341 MB bytes (37.92%)]
[INFO]: 2019/11/16 23:18:22 [transferred 134 MB / 341 MB bytes (39.36%)]
[INFO]: 2019/11/16 23:18:23 [transferred 139 MB / 341 MB bytes (40.85%)]
[INFO]: 2019/11/16 23:18:24 [transferred 144 MB / 341 MB bytes (42.31%)]
[INFO]: 2019/11/16 23:18:25 [transferred 149 MB / 341 MB bytes (43.76%)]
[INFO]: 2019/11/16 23:18:26 [transferred 154 MB / 341 MB bytes (45.17%)]
[INFO]: 2019/11/16 23:18:27 [transferred 159 MB / 341 MB bytes (46.62%)]
[INFO]: 2019/11/16 23:18:28 [transferred 164 MB / 341 MB bytes (48.09%)]
[INFO]: 2019/11/16 23:18:29 [transferred 169 MB / 341 MB bytes (49.48%)]
[INFO]: 2019/11/16 23:18:30 [transferred 174 MB / 341 MB bytes (50.95%)]
[INFO]: 2019/11/16 23:18:31 [transferred 179 MB / 341 MB bytes (52.41%)]
[INFO]: 2019/11/16 23:18:32 [transferred 184 MB / 341 MB bytes (53.87%)]
[INFO]: 2019/11/16 23:18:33 [transferred 188 MB / 341 MB bytes (55.30%)]
[INFO]: 2019/11/16 23:18:34 [transferred 193 MB / 341 MB bytes (56.75%)]
[INFO]: 2019/11/16 23:18:35 [transferred 198 MB / 341 MB bytes (58.18%)]
[INFO]: 2019/11/16 23:18:36 [transferred 202 MB / 341 MB bytes (59.21%)]
[INFO]: 2019/11/16 23:18:37 [transferred 207 MB / 341 MB bytes (60.67%)]
[INFO]: 2019/11/16 23:18:38 [transferred 212 MB / 341 MB bytes (62.12%)]
[INFO]: 2019/11/16 23:18:39 [transferred 217 MB / 341 MB bytes (63.56%)]
[INFO]: 2019/11/16 23:18:40 [transferred 222 MB / 341 MB bytes (65.01%)]
[INFO]: 2019/11/16 23:18:41 [transferred 226 MB / 341 MB bytes (66.46%)]
[INFO]: 2019/11/16 23:18:42 [transferred 231 MB / 341 MB bytes (67.92%)]
[INFO]: 2019/11/16 23:18:43 [transferred 236 MB / 341 MB bytes (69.37%)]
[INFO]: 2019/11/16 23:18:44 [transferred 241 MB / 341 MB bytes (70.78%)]
[INFO]: 2019/11/16 23:18:45 [transferred 246 MB / 341 MB bytes (72.20%)]
[INFO]: 2019/11/16 23:18:46 [transferred 251 MB / 341 MB bytes (73.63%)]
[INFO]: 2019/11/16 23:18:47 [transferred 256 MB / 341 MB bytes (75.07%)]
[INFO]: 2019/11/16 23:18:48 [transferred 261 MB / 341 MB bytes (76.52%)]
[INFO]: 2019/11/16 23:18:49 [transferred 266 MB / 341 MB bytes (77.97%)]
[INFO]: 2019/11/16 23:18:50 [transferred 271 MB / 341 MB bytes (79.41%)]
[INFO]: 2019/11/16 23:18:51 [transferred 276 MB / 341 MB bytes (80.86%)]
[INFO]: 2019/11/16 23:18:52 [transferred 279 MB / 341 MB bytes (81.84%)]
[INFO]: 2019/11/16 23:18:53 [transferred 284 MB / 341 MB bytes (83.27%)]
[INFO]: 2019/11/16 23:18:54 [transferred 289 MB / 341 MB bytes (84.70%)]
[INFO]: 2019/11/16 23:18:55 [transferred 294 MB / 341 MB bytes (86.14%)]
[INFO]: 2019/11/16 23:18:56 [transferred 298 MB / 341 MB bytes (87.60%)]
[INFO]: 2019/11/16 23:18:57 [transferred 303 MB / 341 MB bytes (89.04%)]
[INFO]: 2019/11/16 23:18:58 [transferred 308 MB / 341 MB bytes (90.51%)]
[INFO]: 2019/11/16 23:18:59 [transferred 313 MB / 341 MB bytes (91.96%)]
[INFO]: 2019/11/16 23:19:00 [transferred 318 MB / 341 MB bytes (93.42%)]
[INFO]: 2019/11/16 23:19:01 [transferred 323 MB / 341 MB bytes (94.87%)]
[INFO]: 2019/11/16 23:19:02 [transferred 328 MB / 341 MB bytes (96.34%)]
[INFO]: 2019/11/16 23:19:03 [transferred 333 MB / 341 MB bytes (97.78%)]
[INFO]: 2019/11/16 23:19:04 [transferred 338 MB / 341 MB bytes (99.20%)]
[INFO]: 2019/11/16 23:19:04 [Done]
```
in to something like this:

```
[INFO]: 2019/11/16 23:17:53 [Downloading video 1/3 1080p] 500 MB / 500 MB.................done 
[INFO]: 2019/11/16 23:17:53 [Downloading video 2/3 1080p] 220 MB / 500 MB.................48%  
```

**Comment by RoyalFlyBy** [comment]
It would be a slight pain in the ass to implement but I can probably do that, ETA 1 week

**Comment by Simon01-dummy** [comment]
I would like to report a strange problem in which I stumbled: why a 1080 vid is downloaded and another isn't, @RoyalFlyBy? F.e., I take these random vids from the "other" frontpage (I'm pan):
- https://www.pornhub.com/view_video.php?viewkey=ph5d15d57771a9f
- https://www.pornhub.com/view_video.php?viewkey=ph5d4fe5ff9d41c

The first is teorically downlodable. With the second the result is the follow.
![screen](https://user-images.githubusercontent.com/58144783/69645980-56abd880-1067-11ea-8975-711b774da954.png)
I don't really know where I'm wrong😵.

**Comment by RoyalFlyBy** [comment]
They changed their video distribution again...

I just finished up a project freeing more time for this one. It won't be long

**Comment by RoyalFlyBy** [comment]
Another fix rolling out today for the new video downloading issues, now finally I can focus on improvements and I have quite a few in mind.

**Comment by RoyalFlyBy** [comment]
@onupirat 
How about this for terminal UI?
![demo](https://user-images.githubusercontent.com/50518899/69893175-e4a8ed00-130d-11ea-8bd1-02ddeeb74643.png)

This was a first demo of this feature, ETA and download speed might not be accurate yet.

![demo2](https://user-images.githubusercontent.com/50518899/69893339-41a5a280-1310-11ea-84e2-d1736d9e2fc8.png)

It also supports parallel downloading for videos that were not stored on the same server to allow for maximum speed downloads when downloading lists

**Comment by onupirat** [comment]
Looks good. The parallel download is an awesome idea

**Comment by RoyalFlyBy** [comment]
Pushed out a build that implements all fixes for current issues + the new features, give it a try and let me know
