### ISSUE TITLE
problem with Premium account(s)

### ISSUE THREAD

**Issue by ghost** [RoyalFlyBy/PornHubDownloader#3]
After creating a (more or less temporary) PornHub Premium account, I tried to download a **Premium** video, but the result that I get is the following (I also tried to change the string: the image shows both attempts).
![screen](https://user-images.githubusercontent.com/58144783/69498211-4f5cc180-0ee5-11ea-81a1-8f880982935c.png)
**Where am I wrong**???
I want to point out that if I download a non-Premium video, Your software works _excellently_ (at least for the couple of videos I tried). If You want, @RoyalFlyBy, also use my Premium credentials in the image to do tests, 'cause I won't use them longer.

**Comment by RoyalFlyBy** [comment]
Hi, thank you for your feedback. (and thanks for the credential donation)

Took me a while to find a random Premium video to standardize our tests with but I found one:
https://www.pornhub.com/view_video.php?viewkey=ph5d12746ea6034

I will be on my laptop in an hour or so and I will be anlte to do some testing however for now I seem to notice that the flag used is **-pasword** in both screenshots and I am sure that would also impede it's ability to work as well. (I'm thinking the issue might be bug + misspelled flag)

Could you post me a log for **-password** (double S)?

**Comment by ghost** [comment]
Of course and thank for your proptness, @RoyalFlyBy. 
Here is the results, always with the same temporary account (but with a modified password, 'cause I was notified of an "intrusion": PH was ordering me to change password! To remedy this _veeery annoying_ problem, I post some accounts [here](https://anonfile.com/L5laJ4B1n4/S_rar) that you can use for tests: I hope they still work).
I've used the video you found: https://www.pornhub.com/view_video.php?viewkey=ph5d12746ea6034.
![screen](https://user-images.githubusercontent.com/58144783/69549931-71644b80-0f9a-11ea-9729-eecd75a774b7.png)
I don't really know where I'm wrong.

**Comment by RoyalFlyBy** [comment]
Looks like during the PH update they didn't just change their video distribution but also their login a little bit.

I will definitely be looking into this either today or tomorrow depending on the amount of time I have.

Sorry to hear about the intrusion, I have yet to test anything but I think PH is definitely watching this repository.

**Comment by Simon01-dummy** [comment]
Okay, @RoyalFlyBy: when you've time, look also in the other issue: I wrote there too.

**Comment by RoyalFlyBy** [comment]
Will focus on this issue now. Let's see if I can get login and premium to work again

**Comment by RoyalFlyBy** [comment]
Fixed as well

**Comment by ghost** [comment]
In fact now it works, both with and without login credentials😃: thanks very much for all Your work, @RoyalFlyBy. For now, **I close this issue**; in case the problem arises again, I will reopen it.

**Comment by ghost** [comment]
Unfortunately I've to reopen the issue: after about two weeks off, I wanted to do a check trying to download a PH Premium video that I'd **already successfully** downloaded when You updated the software. 
![Immagine1](https://user-images.githubusercontent.com/58144783/72222744-93288a80-3568-11ea-99f8-555c4441b727.png)
But the result is the following😭: ...
![Immagine1](https://user-images.githubusercontent.com/58144783/72222652-8a838480-3567-11ea-9b17-fbc873715f43.png)
The file «**PHDownloader.log**» says:
```
[DEBUG]:	2020/01/12 18:09:18 Going to log in
[INFO]:	2020/01/12 18:09:20 Logged in successfully
[DEBUG]:	2020/01/12 18:09:20 &{1  https://www.pornhubpremium.com/...}
[DEBUG]:	2020/01/12 18:09:20 Going to visit: https://www.pornhubpremium.com/view_video.php?viewkey=(CODE OF VIDEO)
[DEBUG]:	2020/01/12 18:09:20 Extracted view key: (CODE OF VIDEO)
[FATAL]:	2020/01/12 18:09:20 Unexpected error: 'runtime error: slice bounds out of range'
```
I think PH has changed something🙁...

**Comment by RoyalFlyBy** [comment]
Hey, I will research this tonight.

By the way, you want to censor that URL in the third line of the log excerpt as well out of safety precautions

**Comment by RoyalFlyBy** [comment]
I wasn't able to reproduce this error. Is this happening with all premium videos or just some of them?

**Comment by ghost** [comment]
Welcome back, **@RoyalFlyBy**: I was very worried that something had happened to You but, fortunately, it isn't🙂.
The problem arises when I try (errata corrige: I **tried**, 'cause my Premium subscription has expired) to download some «Paid Videos» from Premium version. The very curious thing is that some vids were downloaded, others didn't🤔.
