### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ghost** [RoyalFlyBy/PornHubDownloader#4]
I tried to download a list of vids (**not** Premium) exactly following Your instructions @RoyalFlyBy; with the 1st yesterday all right, but with the 2nd list nowday, the result is this.
![screen](https://user-images.githubusercontent.com/58144783/69741886-1d916800-113c-11ea-9a0c-e526c570fcce.png)
The same problem happens with single videos of the list, **HDs and/or not**. Where am I wrong😭???

**Comment by RoyalFlyBy** [comment]
I noticed you had written a comment for single videos failing as well. I am rolling out a fix, would you like to try again now?

**Comment by ghost** [comment]
Many thanks for Your solicitude, @RoyalFlyBy.
As You can see from the screenshot below, I tried in every way to download both a video of the collection and the collection complete, before and after logging in, but a mysterious block persists🤔. And, so, I still can't download videos in my `listofvids.txt` file ... 
I don't know where's the trouble.
![screen](https://user-images.githubusercontent.com/58144783/69811222-eaa7ac80-11ed-11ea-94c3-ea9a0570eb5b.png)

**Comment by RoyalFlyBy** [comment]
True I haven't fixed login yet, am going to today hopefully.

**Comment by RoyalFlyBy** [comment]
Fix for login is coming tomorrow (in 12-18 hours from now), that should fix this issue

Stay posted :)

**Comment by RoyalFlyBy** [comment]
Fixed, try it out and let me know

**Comment by ghost** [comment]
I'm doing a lot of testing: for now, everything is all right so, thank You very much for all, @RoyalFlyBy!
P.S .: I'll also go to the _other repository_ You created: I want to try the tool to recorder CT😉(but it's a bit more complicated, 'cause I've Windows) ...

**Comment by BRUHItsABunny** [comment]
I'm debating on working on that one as well, to make installation easier

**Comment by Simon01-dummy** [comment]
For the moment, I'm downloading many videos with the highest quality (1080 px), some of which are exclusively Premium: the corrections You've made work very well, @RoyalFlyBy.
![55](https://user-images.githubusercontent.com/58144783/70794905-06d74c00-1d9f-11ea-973c-f6d9082b563e.gif)
«_Only for Fans_» videos are excluded, from what I see😐(I opened an issue for this: #5).
