### ISSUE TITLE
Unexpected error: 'runtime error: slice bounds out of range' (Fan Only Videos)

### ISSUE THREAD

**Issue by ghost** [RoyalFlyBy/PornHubDownloader#5]
I tried to download an «Only for Fans» video chosen at random: [this one](https://www.pornhub.com/view_video.php?viewkey=ph5beefe058813a). The screen that comes out is the following:
![Screen](https://user-images.githubusercontent.com/58144783/70438745-c15d0b00-1a8e-11ea-88b0-d358e1473787.png)
The file PHDownloader.logreport this:
```
[DEBUG]:	2019/12/14 11:41:22 Going to log in
[INFO]:	2019/12/14 11:41:25 Logged in successfully
[DEBUG]:	2019/12/14 11:41:25 &{1  https://www.pornhubpremium.com/user/login_auto?response=VHyaSl0OV-5FdibsC8Z31gvHVyC9mL6pEdjYMA_2zKIav9LAjbN_LbExNaqHe9vGbDirG09Q7mIjGa75Ex5CCAI_MUbE9u-B2u2HUqDgqGVwzbknIIipEIE2yRFYv7yutcbYayJo_k8Hq5NGuCY9jMZOKSt4Rgn6gVbzgKbsYHZ0EAxUdBy0PBfh4VGfxngme7wdQ4iK2hnmOk5sey6b7ku0cdHp9Z0bdKqtdOUolG8w5Q-GAXCwT99k83nEYRkmQU2e7vqswGibYkBXQAtrX76vdn_nG5mtilXyvdARi3vOPX9ydT3CSVPYqYiP6FwYXGmQZ62FHZlJaOWbcqupM5xUktzp50ZxT_yyGL-PslS8my4OevMImEUwTNyVf8ze3UOjTleXE0uNpSZRC8BII98VAGJ_Ll-qV0DhE5DkRlfWOnlcR0gYbsk_cJV_OnIpIkM972BxaortWPajG2o9WOrjhagRfG9XsE6lJZ-u5B0Jy4W65VBg0kI0dGQIczLdbQS4GgmtI1KqLjRc-BgIL-i4XK1HdGXw23eK2xvYpQ2ZImJR77tRQ0YxZf_k 1 false false VHyaSl0OV-5FdibsC8Z31gvHVyC9mL6pEdjYMA_2zKIav9LAjbN_LbExNaqHe9vGbDirG09Q7mIjGa75Ex5CCAI_MUbE9u-B2u2HUqDgqGVwzbknIIipEIE2yRFYv7yutcbYayJo_k8Hq5NGuCY9jMZOKSt4Rgn6gVbzgKbsYHZ0EAxUdBy0PBfh4VGfxngme7wdQ4iK2hnmOk5sey6b7ku0cdHp9Z0bdKqtdOUolG8w5Q-GAXCwT99k83nEYRkmQU2e7vqswGibYkBXQAtrX76vdn_nG5mtilXyvdARi3vOPX9ydT3CSVPYqYiP6FwYXGmQZ62FHZlJaOWbcqupM5xUktzp50ZxT_yyGL-PslS8my4OevMImEUwTNyVf8ze3UOjTleXE0uNpSZRC8BII98VAGJ_Ll-qV0DhE5DkRlfWOnlcR0gYbsk_cJV_OnIpIkM972BxaortWPajG2o9WOrjhagRfG9XsE6lJZ-u5B0Jy4W65VBg0kI0dGQIczLdbQS4GgmtI1KqLjRc-BgIL-i4XK1HdGXw23eK2xvYpQ2ZImJR77tRQ0YxZf_k}
[DEBUG]:	2019/12/14 11:41:25 Going to visit: https://www.pornhubpremium.com/view_video.php?viewkey=ph5beefe058813a
[DEBUG]:	2019/12/14 11:41:25 Extracted view key: ph5beefe058813a
[FATAL]:	2019/12/14 11:41:26 Unexpected error: 'runtime error: slice bounds out of range'
```
Please @RoyalFlyBy, I wonder if it can be possible bypass the "block", if I've to insert more instructions in the propt or if it's _absolute necessary_ to be fans, in order to download that kind of videos🤔.

**Comment by RoyalFlyBy** [comment]
I will look into this issue on Monday but I may very well be limited in my testing for I am not sure I can access that feature myself

**Comment by ghost** [comment]
From this pov, I apologize admitting that I cannot help You for now, @RoyalFlyBy, because I'm not a «Fan Club» member of anyone nor do I know data of accounts that're😢.

**Comment by RoyalFlyBy** [comment]
No problem, just let me know when you are able to help testing because I myself can't test it in the current context as I have no motivation to get any Only Fans videos as of right now.

That may change in the future.

**Comment by ghost** [comment]
I understand, @RoyalFlyBy: I fear that I'll have to wait for your interest in «Only for Fan» vids, 'cause so far has been **not** possible😩finding a Premium account with subscription to a performer who posts this kind of content. I hope to find it, but I can't tell you neither **if** nor **when**. After all, like my nickname reveals, I'm a dummy ...

Uh, by the way: _I wish you a Merry Christmas and a Happy New Year_ 😃!!

**Comment by RoyalFlyBy** [comment]
> Uh, by the way: _I wish you a Merry Christmas and a Happy New Year_ 😃!!

Happy holidays to you too, very belated my bad
