### ISSUE TITLE
Major update coming soon

### ISSUE THREAD

**Issue by RoyalFlyBy** [RoyalFlyBy/PornHubDownloader#8]
I have started working on another project that forced me to rewrite some download code to make it much more efficient.

This resulted in a separate yet more superior codebase so I will probably have to rethink the entire way I do these downloader kind of programs all together.

I am currently looking into making this more efficient, easier to use and easier to program.

I therefore am planning an update that will deprecate this entire repository.

Peak for the current features I have planned:
1. Multi threaded downloads
2. A graphical user interface
3. A browser backed scraping client
4. A monolithic design, one downloader program that can have multiple plugins for multiple sites (but the plugins will also be standalone downloaders if you only want one plugin)
5. Server design, I had a few people contact me to help them set this up on servers so they download in the cloud without having their home computer or connection getting used. Next update will make that much easier too since this ties in very neatly with the GUI (feature 2)
6. More sites supported, as I'm moving into the plugins ecosystem I will be able to add more sites since making a plugin is less time-consuming

If you have any suggestions be sure to comment them in this thread, they will be considered

**Comment by RoyalFlyBy** [comment]
PH got wrecked, does anyone have any suggestions for what platform/site I should focus on next?

**Comment by BlackMage2** [comment]
can PH not be fixed?

**Comment by RoyalFlyBy** [comment]
I looked into it and I can indeed fix it, ETA unknown though

**Comment by RoyalFlyBy** [comment]
Rewrite scheduled for 1H December

Changes coming:
* Threaded downloads
* PH API vs web scraping (in the past their API was unstable but now it seems stable)
* Non-spamming terminal
* Daemon mode - feeds into the plugin system and GUI system mentioned above, this repository will be designated the "headless plugin" which can run on it's own, but the GUI application will reside elsewhere.
* Each site will be it's own plugin, each plugin will have their own repository
* Versioning and possible version checks
* More insight into the source code and automatic compilation by GitHub (PH API library remains closed source though)
* Smaller binary sizes (may be down to 4-6mb)

I find this approach prevents the repository from being deprecated and still achieve the planned features and overarching goals.

**Comment by RoyalFlyBy** [comment]
Update just dropped
Now that the main structure of the program is somewhat clear, I should be able to take this and implement it for other sites as well.
