### ISSUE TITLE
runtime error: slice bounds out of range [:-2](when trying to download a private video)

### ISSUE THREAD

**Issue by ghost** [RoyalFlyBy/PornHubDownloader#9]
I successfully download a public video at first. 
But this happened when I try to download a private video. 
`C:\Users\80760>D:\githubDownload\PornHubDownloader-master\PHDownloader.exe -URL=https://www.pornhub.com/view_video.php?viewkey=ph5597feee1d81f`

`By (|/)RoyalFlyBy(\|) on GitHub https://github.com/RoyalFlyBy/PornHubDownloader
Status: Resolving video URL's
panic: runtime error: slice bounds out of range [:-2]

goroutine 1 [running]:
PHDownloader/scraper.(*PHWebClient).GetVideo(0xc0001dfb08, 0xc0000202b4, 0xf, 0x1, 0xf, 0xc00034eab0)
        C:/Users/BUNNY/go/src/PHDownloader/scraper/scraper.go:128 +0x1003
main.GetDownloadTasks(0xd47b20, 0x0, 0x0, 0xc0000298c0, 0x1, 0x948122, 0x17, 0xc0001860a0, 0x0, 0x0, ...)
        C:/Users/BUNNY/go/src/PHDownloader/main.go:329 +0x2c5
main.main()
        C:/Users/BUNNY/go/src/PHDownloader/main.go:157 +0xa15`

Any help is appreciated.

**Comment by RoyalFlyBy** [comment]
Sorry for the delayed response.

It will be hard to debug this given the current state of PH's catalogue being almost entirely wiped out and all.
I will keep this issue open, if I can ever get to a situation to test this again I will try and fix this.
Right now I simply do not have an account with access to private videos so this will be hard to recreate.

Out of curiosity (unrelated, you can ignore this question if you want), given PH's demise, what new platform will now take the crown? If I know I will probably put my efforts into making a fully working downloader for that platform instead. 
As of right now I was thinking Xhamster but maybe not; I've been out of the online porn cycle for a while.

**Comment by ghost** [comment]
Thanks for your reply.

That's right. We cant solve this after PH deleted all the private videos.
As for the new platform, maybe Xvideo or Xmaster?  But there are few high quality videos on this two websites.
Clips4sale has a great collection of porn, but I guess it will be difficult to make a downloader for it. LOL
PH is dead. Maybe I will also be out of the online porn cycle. :p
I will keep this issue open, too.

Have a nice day.
